apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
    {{ .Values.deploymentName}}
  namespace:
    {{  .Values.namespace}}
  labels:
    app:
      {{  .Values.deploymentName}}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.spec.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{  .Values.deploymentName}}  
  template:
    metadata:
      labels:
        app: {{  .Values.deploymentName}}  
    spec:
       containers:
         - env:
          {{- range .Values.environment_secret_vars }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: secrets-admin-ui
                  key: {{ .key }}
          {{- end }}
          
          {{- range $key, $value := .Values.environment_vars }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}

           name: {{ .Values.spec.name }}
           image: {{ .Values.image}}
           imagePullPolicy: {{ .Values.imagePullPolicy }}
           ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
